name: testing
on:
  push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/marchirschvogel/ambit:latest
    steps:
      - name: Run Ambit tests
        run: pytest tests
