name: testing
on:
  push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/marchirschvogel/ambit:latest
    steps:
      - name: Checkout Ambit
        run: git clone https://github.com/marchirschvogel/ambit.git
      - name: Switch to Ambit tests folder
        run: cd ambit/tests
      - name: Run Ambit tests
        run: pytest
